### ISSUE TITLE
Missing RSS feed

### ISSUE THREAD

**Issue by tiagoafpereira** [alexharri/website#3]
After reading a few of your posts (“The Engineering behind Figma's Vector Networks” is fascinating) I’m very much interested in any new material that you may end up writing and an RSS feed would be excellent.

I was looking for your website's feed but could not find one. I suppose it does not exist.

**Comment by alexharri** [comment]
Hey @tiagoafpereira, thanks for expressing interest!

You can now find the RSS feed at https://alexharri.com/rss.xml. There's also an RSS link in the footer of the page.
