### ISSUE TITLE
TS starts to supporting `@import` statement

### ISSUE THREAD

**Issue by natsuki-engr** [alexharri/website#9]
Your post about JSDoc is good for me. Thank you.
https://alexharri.com/blog/jsdoc-as-an-alternative-typescript-syntax

Now TS v5.5 and later supports `@import` statement.
If you can, could you add this infomation to your post for visitors who's learning about type-safe development using JSDoc like me?
https://devblogs.microsoft.com/typescript/announcing-typescript-5-5-beta/#type-imports-in-jsdoc
https://github.com/microsoft/TypeScript/pull/57207

**Comment by alexharri** [comment]
I wasn't aware of this, thanks for raising this!

I'll see if I can get to it this weekend or the next.

**Comment by alexharri** [comment]
Updated post to mention the `@import` tag, see 810639421c8bc40782dbebd78fae3f5d325b38bc.

Thanks for pointing this out!

**Comment by natsuki-engr** [comment]
Thank you!
